# Schema for the configuration files of the dblog module.

dblog.settings:
  type: mapping
  label: 'Database logging settings'
  mapping:
    row_limit:
      type: integer
      label: 'Database log messages to keep'
