# Schema for the configuration files of the toolbar module.

toolbar.settings:
  type: mapping
  label: 'Toolbar settings'
  mapping:
    breakpoints:
      type: sequence
      label: 'Breakpoints'
      sequence:
        - type: string

toolbar.breakpoints:
  type: mapping
  label: 'Toolbar breakpoint settings'
  mapping:
    narrow:
      type: string
      label: 'Narrow'
    standard:
      type: string
      label: 'Standard'
    wide:
      type: string
      label: 'Wide'
