id: bartik.footer
weight: '0'
status: '1'
langcode: en
region: footer
plugin: 'system_menu_block:menu-footer'
settings:
  label: 'Footer menu'
  module: system
  label_display: visible
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
