id: field_tags
type: taxonomy_term_reference
module: taxonomy
active: '1'
settings:
  allowed_values:
    -
      vocabulary: tags
      parent: 0
storage:
  type: field_sql_storage
  module: field_sql_storage
  active: '1'
  settings: {  }
locked: '0'
cardinality: '-1'
translatable: '0'
entity_types: {  }
indexes:
  target_id:
    - target_id
status: 1
langcode: und
