id: field_image
type: image
module: image
active: '1'
settings:
  uri_scheme: public
  default_image: false
  column_groups:
    file:
      label: File
      columns:
        - target_id
        - width
        - height
    alt:
      label: Alt
      translatable: true
    title:
      label: Title
      translatable: true
storage:
  type: field_sql_storage
  module: field_sql_storage
  active: '1'
  settings: {  }
locked: '0'
cardinality: '1'
translatable: '0'
entity_types: {  }
indexes:
  target_id:
    - target_id
status: 1
langcode: und
