# Schema for the views display plugins.

views.display.default:
  type: views_display
  label: 'Default display options'

views.display.page:
  type: views_display
  label: 'Page display options'
  mapping:
    path:
      type: string
      label: 'Page path'
    menu:
      type: mapping
      label: 'Menu'
      mapping:
        type:
          type: string
          label: 'Type'
        title:
          type: text
          label: 'Title'
        description:
          type: text
          label: 'Description'
        weight:
          type: integer
          label: 'Weight'
        name:
          type: string
          label: 'Menu name'
        context:
          type: string
          label: 'Context'
    tab_options:
      type: mapping
      label: 'Tab options'
      mapping:
        type:
          type: string
          label: 'Type'
        title:
          type: text
          label: 'Title'
        description:
          type: text
          label: 'Description'
        weight:
          type: integer
          label: 'Weight'
        name:
          type: string
          label: 'Menu name'

views.display.block:
  type: views_display
  label: 'Block display options'
  mapping:
    block_description:
      type: text
      label: 'Block name'
    block_caching:
      type: boolean
      label: 'Block caching'

views.display.feed:
  type: views_display
  label: 'Feed display options'
  mapping:
    path:
      type: string
      label: 'Page path'
    sitename_title:
      type: boolean
      label: 'Use the site name for the title'
    displays:
      type: sequence
      label: 'The feed icon will be available only to the selected displays.'
      sequence:
        - type: string
          label: 'Display'

views.display.embed:
  type: views_display
  label: 'Embed display options'

views.display.attachment:
  type: views_display
  label: 'Attachment display options'
  mapping:
    displays:
      type: sequence
      label: 'Attach to'
      sequence:
        - type: string
          label: 'Display'
    attachment_position:
      type: string
      label: 'Attachment position'
    inherit_arguments:
      type: boolean
      label: 'Inherit contextual filters'
    inherit_exposed_filters:
      type: boolean
      label: 'Inherit exposed filters'
    inherit_pager:
      type: boolean
      label: 'Inherit pager'
    render_pager:
      type: boolean
      label: 'Render pager'
