# Schema for the views area plugins.

views.area.*:
  type: views_area
  label: 'Default area'

views.area.text:
  type: views_area
  label: 'Text'
  mapping:
    content:
      type: text
      label: 'The shown text of the area'
    format:
      type: string
      label: 'The filter format the content is in'
    tokenize:
      type: boolean
      label: 'Should replacement tokens be used from the first row'

views.area.text_custom:
  type: views_area
  label: 'Text custom'
  mapping:
    content:
      type: text
      label: 'The shown text of the area'
    tokenize:
      type: boolean
      label: 'Should replacement tokens be used from the first row'

views.area.result:
  type: views_area
  label: 'Result'
  mapping:
    content:
      type: text
      label: 'The shown text of the result summary area'


views.area.title:
  type: views_area
  label: 'Title'
  mapping:
    title:
      type: label
      label: 'The title which will be overridden for the page'

views.area.view:
  type: views_area
  label: 'View'
  mapping:
    view_to_insert:
      type: string
      label: 'View to insert'
    inherit_to_arguments:
      type: boolean
      label: 'Inherit contextual filters'
