favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: '1'
features:
  comment_user_picture: '1'
  comment_user_verification: '1'
  favicon: '1'
  logo: '1'
  name: '1'
  node_user_picture: '1'
  main_menu: '1'
  secondary_menu: '1'
  slogan: '1'
logo:
  path: ''
  url: ''
  use_default: '1'
