base_field: nid
base_table: node
core: '8'
description: 'A list of months that link to content for that month.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_tags: {  }
      title: 'Monthly archive'
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      sorts:
        created:
          id: created
          table: node_field_data
          field: created
          order: DESC
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exposed: '0'
          expose:
            label: ''
          granularity: second
          provider: views
      arguments:
        created_year_month:
          id: created_year_month
          table: node_field_data
          field: created_year_month
          default_action: summary
          exception:
            title_enable: '1'
          title_enable: '1'
          title: '%1'
          default_argument_type: fixed
          summary:
            sort_order: desc
            format: default_summary
          summary_options:
            override: '1'
            items_per_page: '30'
          specify_validation: '1'
          plugin_id: date_year_month
          provider: views
      filters:
        status:
          id: status
          table: node_field_data
          field: status
          value: '1'
          group: '0'
          expose:
            operator: '0'
          plugin_id: boolean
          provider: views
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          uses_fields: '0'
      row:
        type: 'entity:node'
        options:
          view_mode: teaser
          links: '1'
          comments: '0'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      fields: {  }
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: archive
  block_1:
    id: block_1
    display_title: Block
    display_plugin: block
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
      defaults:
        arguments: '0'
      arguments:
        created_year_month:
          id: created_year_month
          table: node_field_data
          field: created_year_month
          default_action: summary
          exception:
            title_enable: '1'
          title_enable: '1'
          title: '%1'
          default_argument_type: fixed
          summary:
            format: default_summary
          summary_options:
            items_per_page: '30'
          specify_validation: '1'
          plugin_id: date_year_month
          provider: views
label: Archive
module: node
id: archive
tag: default
langcode: en
