base_field: nid
base_table: node
core: '8'
description: 'Customize the default taxonomy/term display.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_tags: {  }
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      sorts:
        sticky:
          id: sticky
          table: node_field_data
          field: sticky
          order: DESC
          plugin_id: standard
          relationship: none
          group_type: group
          admin_label: ''
          exposed: '0'
          expose:
            label: ''
          provider: views
        created:
          id: created
          table: node_field_data
          field: created
          order: DESC
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exposed: '0'
          expose:
            label: ''
          granularity: second
          provider: views
      arguments:
        term_node_tid_depth:
          id: term_node_tid_depth
          table: node
          field: term_node_tid_depth
          default_action: 'not found'
          exception:
            title_enable: '1'
          title_enable: '1'
          title: '%1'
          default_argument_type: fixed
          summary:
            format: default_summary
          specify_validation: '1'
          validate:
            type: taxonomy_term
          depth: '0'
          break_phrase: '1'
          plugin_id: taxonomy_index_tid_depth
          relationship: none
          group_type: group
          admin_label: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_options: {  }
          default_argument_skip_url: '0'
          summary_options: {  }
          validate_options: {  }
          set_breadcrumb: '0'
          use_taxonomy_term_path: '0'
          provider: taxonomy
        term_node_tid_depth_modifier:
          id: term_node_tid_depth_modifier
          table: node
          field: term_node_tid_depth_modifier
          exception:
            title_enable: '1'
          default_argument_type: fixed
          summary:
            format: default_summary
          specify_validation: '1'
          plugin_id: taxonomy_index_tid_depth_modifier
          relationship: none
          group_type: group
          admin_label: ''
          default_action: ignore
          title_enable: '0'
          title: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_options: {  }
          default_argument_skip_url: '0'
          summary_options: {  }
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          provider: taxonomy
      filters:
        status_extra:
          id: status_extra
          table: node_field_data
          field: status_extra
          group: '0'
          expose:
            operator: '0'
          plugin_id: node_status
          provider: node
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          uses_fields: '0'
      row:
        type: 'entity:node'
        options:
          view_mode: teaser
          links: '1'
          comments: '0'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      fields: {  }
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: taxonomy/term/%
  feed_1:
    id: feed_1
    display_title: Feed
    display_plugin: feed
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
      pager:
        type: full
        options:
          items_per_page: '15'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      path: taxonomy/term/%/%/feed
      displays:
        page: page
        default: '0'
      style:
        type: rss
        options:
          description: ''
          grouping: {  }
          uses_fields: '0'
      row:
        type: node_rss
        options:
          relationship: none
          item_length: default
          links: '0'
label: 'Taxonomy term'
module: taxonomy
id: taxonomy_term
tag: default
langcode: en
