base_field: nid
base_table: node
core: '8'
description: 'A list of all content, by letter.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_tags: {  }
      use_ajax: '1'
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: '36'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          link_to_node: '1'
          plugin_id: node
          relationship: none
          group_type: group
          admin_label: ''
          label: Title
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          provider: node
        name:
          id: name
          table: users
          field: name
          label: Author
          link_to_user: '1'
          relationship: uid
          plugin_id: user_name
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          overwrite_anonymous: '0'
          anonymous_text: ''
          format_username: '1'
          provider: user
        changed:
          id: changed
          table: node_field_data
          field: changed
          label: 'Last update'
          date_format: long
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          custom_date_format: ''
          timezone: ''
          provider: views
      arguments:
        title:
          id: title
          table: node_field_data
          field: title
          default_action: default
          exception:
            title_enable: '1'
          default_argument_type: fixed
          default_argument_options:
            argument: a
          summary:
            format: default_summary
          specify_validation: '1'
          glossary: '1'
          limit: '1'
          case: upper
          path_case: lower
          transform_dash: '0'
          plugin_id: string
          relationship: none
          group_type: group
          admin_label: ''
          title_enable: '0'
          title: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_skip_url: '0'
          summary_options: {  }
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: '0'
          provider: views
      relationships:
        uid:
          id: uid
          table: node_field_data
          field: uid
          plugin_id: standard
          relationship: none
          group_type: group
          admin_label: author
          required: '0'
          provider: views
      style:
        type: table
        options:
          columns:
            title: title
            name: name
            changed: changed
          default: title
          info:
            title:
              sortable: '1'
              separator: ''
            name:
              sortable: '1'
              separator: ''
            changed:
              sortable: '1'
              separator: ''
          override: '1'
          sticky: '0'
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          uses_fields: '0'
          order: asc
          summary: ''
          empty_table: '0'
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: '0'
          default_field_elements: '1'
      header: {  }
      footer: {  }
      empty: {  }
      sorts: {  }
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: glossary
      menu:
        type: normal
        title: Glossary
        weight: '0'
  attachment_1:
    id: attachment_1
    display_title: Attachment
    display_plugin: attachment
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
      pager:
        type: none
        options:
          offset: '0'
          items_per_page: '0'
      defaults:
        arguments: '0'
      arguments:
        title:
          id: title
          table: node_field_data
          field: title
          default_action: summary
          exception:
            title_enable: '1'
          default_argument_type: fixed
          default_argument_options:
            argument: a
          summary:
            format: unformatted_summary
          summary_options:
            items_per_page: '25'
            inline: '1'
            separator: ' | '
          specify_validation: '1'
          glossary: '1'
          limit: '1'
          case: upper
          path_case: lower
          transform_dash: '0'
          plugin_id: string
          relationship: none
          group_type: group
          admin_label: ''
          title_enable: '0'
          title: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_skip_url: '0'
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: '0'
          provider: views
      displays:
        default: default
        page_1: page_1
      inherit_arguments: '0'
label: Glossary
module: node
id: glossary
tag: default
langcode: en
