base_field: iid
base_table: aggregator_item
core: 8.x
description: ''
status: '1'
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      style:
        type: default
      row:
        type: 'entity:aggregator_item'
      fields:
        iid:
          table: aggregator_item
          field: iid
          id: iid
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Item ID'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
      filters: {  }
      sorts: {  }
      title: 'Aggregator RSS feed'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      arguments: {  }
  feed_items_per_category:
    display_plugin: feed
    id: feed_items_per_category
    display_title: 'Feed per category'
    position: '2'
    display_options:
      path: aggregator/rss/%
      display_description: ''
      arguments:
        cid:
          id: cid
          table: aggregator_category
          field: cid
          relationship: none
          group_type: group
          admin_label: ''
          default_action: 'not found'
          exception:
            value: all
            title_enable: '0'
            title: All
          title_enable: '0'
          title: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: '0'
          summary_options:
            base_path: ''
            count: '1'
            items_per_page: '25'
            override: '0'
          summary:
            sort_order: asc
            number_of_records: '0'
            format: default_summary
          specify_validation: '0'
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: '0'
          not: '0'
          plugin_id: aggregator_category_cid
      defaults:
        arguments: '0'
  feed_items:
    display_plugin: feed
    id: feed_items
    display_title: Feed
    position: '2'
    display_options:
      path: aggregator/rss
      display_description: ''
      defaults:
        arguments: '1'
label: 'Aggregator RSS feed'
module: views
id: aggregator_rss_feed
tag: aggregator
uuid: 7dfa5cb7-2248-4d52-8c00-cd8e02d1e78e
langcode: en
