# Enable all methods on nodes.
resources:
  entity:node:
    GET: { }
    POST: { }
    PATCH: { }
    DELETE: { }

# To enable only specific formats for an operation, list the supported_formats.
# For example, the following config makes JSON the only format available for
# node GET requests.
#   resources:
#     entity:node:
#       GET:
#         supported_formats:
#           - json
#
# To enable only specific authentication methods for an operation, list them
# at supported_auth.
# For example, the following config only allows Basic HTTP authenticated
# requests for the POST method on the node entity.
#   resources:
#     entity:node:
#       POST:
#         supported_auth:
#           - http_basic
